Dev board
ut-ras/robomaster_hardware pull request #6
Opened 2023-11-18 00:33 UTC by StephanGalvez

lakshay changes: aligned mounting holes and currently fixing test points

2023-11-18 01:03 UTC, LeftistTachyon requested changes
Good work so far! I bet it was difficult getting the physical dimensions down, and there's just a few nitpicks until you're good to go!

2023-11-18 01:03 UTC, LeftistTachyon commented on Dev_Board/Dev_Board.kicad_pcb
> +(kicad_pcb (version 20221018) (generator pcbnew)
Make sure you're following JLCPCB's manufacturing capabilities. You can check these on the website, and I've went ahead and added them to your board & made it compliant to their capabilities.

2023-11-18 01:06 UTC, StephanGalvez commented on Dev_Board/Dev_Board.kicad_pcb
> +(kicad_pcb (version 20221018) (generator pcbnew)
fixed em

2023-11-24 23:39 UTC, Lakshay983 commented
Everything is there and would work, but there are a lot of issues with readability and neatness that will improve board usability and debugging

Here are some of my suggestions for improving the schematic readability:
- <img width="1126" alt="Screenshot 2023-11-24 at 5 02 33 PM" src="https://github.com/ut-ras/robomaster_hardware/assets/56173382/916d4981-b670-412c-b6cb-d9dfb3ead219"> things like GND and PWR shouldn't be regular labels. There are symbols for them that exist in KiCAD. The GND symbol is just called GND and for power, you can look it up in the symbol menu as well (3.3V or 24V)
- <img width="616" alt="Screenshot 2023-11-24 at 5 12 03 PM" src="https://github.com/ut-ras/robomaster_hardware/assets/56173382/3e8ae41f-e904-4dbf-a4c1-666db394db2c"> Not too big of a fan of the horizontal connectors, I'd suggest flipping them and making them vertical that way you can make sure your labels can always be seen. (C3, B3, and A3 are covered up in the left connector).
- Try labeling what connections are coming in from the Devboard and what connections are being sent out. Check the Turret schematic for a similar example.

Layout stuff:

- <img width="132" alt="Screenshot 2023-11-24 at 5 18 09 PM" src="https://github.com/ut-ras/robomaster_hardware/assets/56173382/902df6f0-8acf-4f9f-bbba-9f7afeee9c84"> this test point is still on the bottom layer (indicated by blue) so it won't be accessibly while this board is stacked on top of the dev board
-  <img width="354" alt="Screenshot 2023-11-24 at 5 19 00 PM" src="https://github.com/ut-ras/robomaster_hardware/assets/56173382/b30141dc-b1c7-4b7e-b610-34639a801373"> what happened to the mounting holes???
- For any test points I'd like to see silkscreen labels as to what they're measuring
-  <img width="450" alt="Screenshot 2023-11-24 at 5 21 58 PM" src="https://github.com/ut-ras/robomaster_hardware/assets/56173382/76a57089-c64f-4cbb-9c76-e69e9908aa26"> 
<img width="584" alt="Screenshot 2023-11-24 at 5 22 15 PM" src="https://github.com/ut-ras/robomaster_hardware/assets/56173382/d5d66070-18ab-442b-bc8c-12ef3345e7de">  The "Out_Port" silkscreens are on different sides and not aligned. Please pick one side and ensure that any silkscreen that needs to be read while the board is in use is on the top side (bottom text will not be visible while the dev board is not connected)
- Instead of writing "Out_Port" for connector names please put what their function is. If they're just generic connectors then that's fine, but if it's say a power connector, a can connector, or a signal connector then please label it so. I.e if there's an intended purpose for the connector then put that on the silkscreen
- None of the test points are aligned. For aligning stuff you can select the components, right-click them, "Align/Distribute" -> "Align to Center" (horizontal or vertical center depending on which way you want to align it)

If you have any questions then please let me know! Don't take what I say for fact, you worked on this board not me so there may be some considerations I don't know.

2024-09-17 06:28 UTC, closed without merging